[font]
size = 16.0

[font.normal]
family = "firacode nerd font"

[env]
term = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless" # Needed for Mac
opacity = 0.8
blur = true

[general]
import = ["tokyo-night.toml"]



