[font]
size = 12.0

[font.normal]
style = "Regular"
family = "FiraCode Nerd Font"

[env]
term = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless" # Needed for Mac
opacity = 0.8
blur = true

[general]
import = ["tokyo-night.toml"]

[mouse]
hide_when_typing = true





